### ISSUE TITLE
error in mysql import script

### ISSUE THREAD

**Issue by drego83** [robske110/IDDataLogger#1]
Hi,

tomorrow morning I tried to test the install/config script. It runs through successfully, but after starting, I got some errors.

Why?
the script db_mysql.sql contains errors:
CREATE TABLE IF NOT EXISTS users (
    userid serial NOT NULL PRIMARY KEY,
    username text UNIQUE NOT NULL,
    hash text NOT NULL
);

-> username with type text can't be unique!
Please use varchar(20) or varchar(40) as type

Regards
drego

**Comment by robske110** [comment]
Interesting, my MySQL version (MariaDB 10.5) didn't complain.

**Comment by drego83** [comment]
Iam using:
Server-Typ: MySQL
Server-Version: 5.7.33-0ubuntu0.16.04.1 - (Ubuntu)
