### ISSUE TITLE
Creating a new user at installation does not work

### ISSUE THREAD

**Issue by simonCGN** [robske110/IDDataLogger#10]
At installation answering Y when asked wether to create a new user for the web interface it does not prompt for either username nor for password.
The script responds with: Perfect! Server will not continue starting...

**Comment by robske110** [comment]
Did you enter an uppercase „Y“?
You can retry with `./start.sh --wizzard`.

**Comment by simonCGN** [comment]
Ha, that resolved the issue. Thank you

**Comment by robske110** [comment]
The wizards now do not fall through on invalid entry anymore :)
