### ISSUE TITLE
Formatting of time

### ISSUE THREAD

**Issue by simonCGN** [robske110/IDDataLogger#11]
Hi,

in the iOS widget the time needs to be changed. Also some info of that is what would be helpful.

For me it shows:

10K (I suppose that is the charging speed?)
1:29.1290500000 (Formatting wrong; is the the remaining tim till fill charge?
007h (Formatting and also not sure what is shows; see screenshots, it shows 35h in one screenshot and two hours later it shows 007h)

Best regards

Simon

(BTW, great project, also managed to replace the default red icon with a custom one meanwhile)
![IMG_8378b](https://user-images.githubusercontent.com/31488296/112658808-12476d00-8e54-11eb-9163-08a644e598e0.jpg)
![IMG_8375](https://user-images.githubusercontent.com/31488296/112658812-14113080-8e54-11eb-97d4-1e4931c3fe41.jpg)

**Comment by robske110** [comment]
Oh, I forgot to make a release for some fixes in the widget. Please delete the widget and download the new scriptable file from https://github.com/robske110/IDDataLogger/releases/tag/v0.0.4
The red square indicates a failure while getting the correct car Picture from VW. Could you delete/rename the file `data/carPic.png` and then start start.sh and share its output?

**Comment by simonCGN** [comment]
That is the output:

pi@raspberrypi:~/IDDataLogger $ ./start.sh 
Loading Logger...
21:04:45.795287 [INFO] Starting ID DataLogger Version v0.0.4-InDev (aefebb0b23627eb65b23824e8e89222870f4e821)...
Loading Main...
21:04:45.803406 [INFO] Reading config...
21:04:45.803591 [INFO] Connecting to db...
Loading DatabaseConnection...
Loading CarPictureHandler...
Loading QueryCreationHelper...
Loading CarStatusFetcher...
21:04:45.843183 [INFO] Logging in...
Loading LoginInformation...
Loading CurlWrapper...
Loading API...
Loading MobileAppAPI...
Loading HTTPUtils...
Loading Form...
Loading IDAPIException...
Loading IDLoginException...
Loading ErrorUtils...
21:04:47.177566 [CRITICAL] robske_110\vwid\api\exception\IDLoginException: "Unable to login. Check login information (password)! (Could not find location header.)" (EXCEPTION) in "/home/pi/IDDataLogger/src/vwid/api/MobileAppAPI.php" at line 74
21:04:47.178087 [EMERGENCY] CRASHED WHILE STARTING; TRYING TO SHUTDOWN SAFELY
21:04:47.178287 [INFO] Shutting down...
21:04:47.178462 [CRITICAL] Forcibly shutting down while starting!
pi@raspberrypi:~/IDDataLogger $

**Comment by robske110** [comment]
That log indicates that the file `data/carPic.png` was still in place and also that login failed. But in the widget you obviously already had some data, did you change the credentials?
Can you check if the credentials in `config/config.json` are correct and then run the following commands in sequence?:
```bash
sudo systemctl stop iddatalogger.service
cd ~/IDDataLogger
mv ./data/carPic.png ./data/carPic-backup.png
./start.sh # please share the output of this command and terminate it with CTRL+C after about 20secs
sudo systemctl start iddatalogger.service
```

**Comment by simonCGN** [comment]
I did not change any credentials at Volkswagen.
To ensure the password was correct I logged in successfully into VWs website. And here was probably the problem. The website prompted me for consent to some privacy data (again as I have given it already when registering obviously).

I just need to wait until the iOS widget pulls the new pic but I can see it. There is some caching going on either in scriptable or iOS.



After that I got no errors anymore. Here is the output now:
Loading Logger...
07:30:22.576785 [INFO] Starting ID DataLogger Version v0.0.4-InDev (aefebb0b23627eb65b23824e8e89222870f4e821-dirty)...
Loading Main...
07:30:22.585061 [INFO] Reading config...
07:30:22.585290 [INFO] Connecting to db...
Loading DatabaseConnection...
Loading CarPictureHandler...
07:30:22.619199 [INFO] Fetching carPicture (this will take a while...)
Loading CurlWrapper...
Loading API...
Loading WebsiteAPI...
Loading LoginInformation...
Loading HTTPUtils...
Loading Form...
07:30:31.518859 [INFO] Successfully cropped and saved picture
Loading QueryCreationHelper...
Loading CarStatusFetcher...
07:30:31.663721 [INFO] Logging in...
Loading MobileAppAPI...
Loading CarStatusWriter...
07:30:33.866629 [INFO] Done. Startup took 11.314305067062s
07:30:33.866934 [INFO] Ready!
07:30:33.867321 [INFO] Fetching car status...
07:30:34.243250 [INFO] Writing new data for timestamp 2021-03-26T19:57:26







--------------------------------------------
Just for good measure, here is the output before the problem was fixed:

Loading Logger...
07:20:26.583713 [INFO] Starting ID DataLogger Version v0.0.4-InDev (aefebb0b23627eb65b23824e8e89222870f4e821-dirty)...
Loading Main...
07:20:26.591957 [INFO] Reading config...
07:20:26.592138 [INFO] Connecting to db...
Loading DatabaseConnection...
Loading CarPictureHandler...
07:20:26.625573 [INFO] Fetching carPicture (this will take a while...)
Loading CurlWrapper...
Loading API...
Loading WebsiteAPI...
Loading LoginInformation...
Loading HTTPUtils...
Loading Form...
Loading IDAPIException...
Loading IDAuthorizationException...
Loading ErrorUtils...
07:20:28.840822 [CRITICAL] robske_110\vwid\api\exception\IDAuthorizationException: "Not authorized to execute API request 'https://www.volkswagen.de/app/authproxy/vw-de/tokens' (httpCode 401)" (EXCEPTION) in "/home/pi/IDDataLogger/src/vwid/api/API.php" at line 16
07:20:28.841227 [WARNING] Failed to automatically fetch the carPicture! You can substitute data/carPic.png manually.
Loading QueryCreationHelper...
Loading CarStatusFetcher...
07:20:28.855711 [INFO] Logging in...
Loading MobileAppAPI...
Loading IDLoginException...
07:20:29.942849 [CRITICAL] robske_110\vwid\api\exception\IDLoginException: "Unable to login. Check login information (password)! (Could not find location header.)" (EXCEPTION) in "/home/pi/IDDataLogger/src/vwid/api/MobileAppAPI.php" at line 74
07:20:29.943222 [EMERGENCY] CRASHED WHILE STARTING; TRYING TO SHUTDOWN SAFELY
07:20:29.943404 [INFO] Shutting down...
07:20:29.943573 [CRITICAL] Forcibly shutting down while starting!
pi@raspberrypi:~/IDDataLogger $

**Comment by simonCGN** [comment]
Besides, the iOS widget writes a log. Not sure why as I have not seen this behaviour in other widgets that I use:

2021-03-27 07:47:58: {"time":"2021-03-26T19:57:26+01:00","batterySOC":"65","remainingRange":295,"remainingChargingTime":0,"chargeState":"readyForCharging","chargePower":"0.0","chargeRateKMPH":0,"targetSOC":"100","plugConnectionState":"disconnected","plugLockState":"unlocked","remainClimatisationTime":0,"hvacState":"off","hvacTargetTemp":"19.0","lastChargeStartTime":"2021-03-26T08:53:23+01:00"}

Perhaps you have configured it to do so.

**Comment by robske110** [comment]
Ah, great! I will document that one might need to login and give consent for some privacy policies.
The iOS widget does indeed cache the image. Please set [forceImageRefresh](https://github.com/robske110/IDDataLogger/blob/master/docs/ioswidget.md#more-settings) to true for a while. (Remember to set it to false, else the image will be fetched on every update of the widget, which is bad for mobile data.)
The log is just for debugging, you can safely ignore it.
