### ISSUE TITLE
Remaining charging time not shown correctly

### ISSUE THREAD

**Issue by simonCGN** [robske110/IDDataLogger#12]
Some negative strange number is shown for remaining charging time, see attached screenshot.

![IMG_8397](https://user-images.githubusercontent.com/31488296/112735009-9b8c9b80-8f49-11eb-895d-60e4f2b8b76c.jpg)

**Comment by robske110** [comment]
First thoughts are timezone issues (it seems 1 hour off and in the wrong direction). Can you show the scriptable log output during the charging session?

**Comment by simonCGN** [comment]
Sure, will take some time until I will have to charge though.

Another idea is Daylight Savings Time where it has already been changed in the US for example whereas in Europe it only changed last night.

**Comment by robske110** [comment]
It could very well have to do something with that. What timezone are you in?

**Comment by simonCGN** [comment]
CEST as of today

**Comment by simonCGN** [comment]
So here is the output while charging:

￼ 2021-04-05 10:29:45: {"time":"2021-04-05T08:28:54+02:00","batterySOC":"6","remainingRange":26,"remainingChargingTime":405,"chargeState":"charging","chargePower":"10.5","chargeRateKMPH":47,"targetSOC":"100","plugConnectionState":"connected","plugLockState":"locked","remainClimatisationTime":0,"hvacState":"off","hvacTargetTemp":"19.0","lastChargeStartTime":"2021-04-05T08:26:53+02:00"}

**Comment by simonCGN** [comment]
Here are the screenshots![image](https://user-images.githubusercontent.com/31488296/113556282-8c1dea00-95fc-11eb-9566-b1e514e8e10b.png)

**Comment by simonCGN** [comment]
![image](https://user-images.githubusercontent.com/31488296/113556402-b5d71100-95fc-11eb-8a71-f1a22deb489a.jpeg)

**Comment by simonCGN** [comment]
While the widget

**Comment by robske110** [comment]
I tried to fix this issue. Please check if it still occurs with the latest update.
You can also download a new version of the widget from here: https://github.com/robske110/IDDataLogger/blob/master/Car.js and set the variable/option timetravel to 1617611819. This will force the widget to (temporarily) display the values as if it was run at that time, allowing you to see if it is fixed without needing to wait for the next charge session again.

**Comment by simonCGN** [comment]
Time travel sounds like fun.

Unfortunately did not fix the issue.

Output:

2021-04-05 22:31:47: {"time":"2021-04-05T08:32:17+02:00","batterySOC":"7","remainingRange":29,"remainingChargingTime":400,"chargeState":"charging","chargePower":"10.0","chargeRateKMPH":47,"targetSOC":"100","plugConnectionState":"connected","plugLockState":"locked","remainClimatisationTime":0,"hvacState":"off","hvacTargetTemp":"19.0","lastChargeStartTime":"2021-04-05T08:26:53+02:00"}

**Comment by simonCGN** [comment]
![Uploading 113623672...]

**Comment by simonCGN** [comment]
![image](https://user-images.githubusercontent.com/31488296/113623718-054e2900-965f-11eb-9a44-4627778457e2.png)

**Comment by robske110** [comment]
Did you also update the server side?
The IDView website should now display "v0.0.5-InDev" in the lower lefthand corner.
<img width="319" alt="image" src="https://user-images.githubusercontent.com/16020100/113624040-6f66ce00-965f-11eb-99e9-899ed3e3a5ad.png">

**Comment by simonCGN** [comment]
Thank for the remainder. While updating the server I got:

pi@raspberrypi:~ $ cd ~/IDDataLogger && ./docs/update.sh
Aktualisiere aefebb0..5f09ea8
error: Ihre lokalen Änderungen in den folgenden Dateien würden durch den Merge
überschrieben werden:
	docs/certbot.sh
Bitte committen oder stashen Sie Ihre Änderungen, bevor Sie mergen.
Abbruch
Update complete!
pi@raspberrypi:~/IDDataLogger $

And it still shows v0.0.4-InDev

**Comment by robske110** [comment]
please enter `git reset --hard` before executing update.sh

**Comment by simonCGN** [comment]
One thing leads to another; when I do "git reset --hard" I get "HEAD ist jetzt bei aefebb0 docker: Fix wrong command in update documentation". I did google the error but was not able to find anything.

**Comment by robske110** [comment]
that's not an error, just an informative message. You can now simply execute update.sh

**Comment by simonCGN** [comment]
Successfully updated the server side.

The widget shows the correct amount of time now.
Thank you for fixing it!

It is a very useful widget. I like it a lot as it shows all relevant/availabe information at a glance.
