### ISSUE TITLE
Apache issues while using the install script

### ISSUE THREAD

**Issue by ArthurBijGithub** [robske110/IDDataLogger#13]
Hi, I'm quite new to Github, so apologies up front if this is not the way to address these issues.
I'm trying to install this IDDatyalogger on a fresh configured Pi 1 model B (with 8Gb SD-card).
While running the script I see some error-like messages (**_Bold and Italic_** parts are shown in red):

> invoke-rc.d: initscript apache2, action "start" failed.
> ● apache2.service - The Apache HTTP Server
>    Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
>    Active: **_failed_** (Result: exit-code) since Thu 2021-04-15 21:55:14 CEST; 214ms ago
>      Docs: https://httpd.apache.org/docs/2.4/
>   Process: 10851 ExecStart=/usr/sbin/apachectl start **_(code=exited, status=132)_**
> 
> Apr 15 21:55:14 raspberrypi systemd[1]: Starting The Apache HTTP Server...
> Apr 15 21:55:14 raspberrypi apachectl[10851]: Illegal instruction
> Apr 15 21:55:14 raspberrypi apachectl[10851]: Action 'start' failed.
> Apr 15 21:55:14 raspberrypi apachectl[10851]: The Apache error log may have more information.
> Apr 15 21:55:14 raspberrypi systemd[1]: apache2.service: Control process exited, code=exited, status=132/n/a
> Apr 15 21:55:14 raspberrypi systemd[1]: apache2.service: Failed with result 'exit-code'.
> Apr 15 21:55:14 raspberrypi systemd[1]: **_Failed to start The Apache HTTP Server_**.
> 

Further on it says:

 

> pg_ctlcluster 11 main start
> 
> Ver Cluster Port Status Owner    Data directory              Log file
> **_11  main    5432 down   postgres /var/lib/postgresql/11/main /var/log/postgresql/postgresql-11-main.log_**
> 

There is no question for username and password and entering 'cd IDDataLogger && ./start.sh' as suggested in the last line gives an error.

I hope there is something I can do to resolve this. If I can help by testing updated versions please let me know.
This is the full output: [pi.docx](https://github.com/robske110/IDDataLogger/files/6321046/pi.docx)

**Comment by ArthurBijGithub** [comment]
Running through the apache error codes I found that (code=exited, status=132) can refer to too old hardware. Could this be the case? In that case it's something you can add to the documentation (and I'll start looking for a new RPi).

**Comment by robske110** [comment]
Hi! Yes, unfortunately the PI 1 is not supported. One can theoretically run this software on it by compiling certain software on it, but that is a very lengthy and somewhat complicated process.

I just added the list of supported PIs yesterday actually, it can be found here: https://github.com/robske110/IDDataLogger/wiki/Supported-Raspberry-PI-models

New Raspberry PIs are currently unfortunately "expensive" (as is everything with the global supply shortage), but if you are looking for a new one mainly for running this project, I would advise against the Pi 4 and buy a Pi 3 instead, as it is more cost-effective.

If you have any remaining questions don't hesitate to ask!

**Comment by ArthurBijGithub** [comment]
Thanks for your swift response. I'll move to the Pi 3.
