### ISSUE TITLE
Error at 'Finishing set up' during manual installation

### ISSUE THREAD

**Issue by ArthurBijGithub** [robske110/IDDataLogger#14]
Just got my new RPi4 and I'm now going through the manual installation. Most of it works well and now I'm at:

> **Finishing set up**
> 
> Make sure to be in the IDDataLogger directory. If you installed using the install script you will need to enter cd ./IDDataLogger. If you come from the manual installation you should already be at the correct location.
> 
> You can now enter ./start.sh, which will start the ID DataLogger. It will now ask you if you want to generate an API key. If you want to use the iOS widget you will need to answer with Y. For more information on setting up the iOS widget using the API key see Setting up the iOS Widget. After that it will ask you if you want to create an user. This user is used to log into the website. Make sure to choose a strong and long password. It is recommended to store this in a password manager. Note that you can create additional API keys or add additional users at any time using ./start.sh --wizard.
> 
> After creating the API key and the user you should see Done. Ready! Fetching car status... and Writing new data for timestamp.

At this last point I get error messages. The terminal shows at the point of entering the username and password:

> Enter the username for the new user: A_USERNAME
> Now enter the password for the new user: A_PASSWORD
> Loading QueryCreationHelper...
> Successfully created the user! Please remember the username and password!
> Perfect! Server will now continue starting...
> Loading CurlWrapper...
> Loading API...
> Loading CarPictureHandler...
> 21:31:01.275602 [INFO] Fetching carPicture (this will take a while...)
> Loading WebsiteAPI...
> Loading LoginInformation...
> Loading HTTPUtils...
> Loading Form...
> Loading ErrorUtils...
> 21:31:02.941800 [CRITICAL] TypeError: "robske_110\webutils\Form::__construct(): Argument #1 ($ele) must be of type DOMElement, null given, called in /home/pi/IDDataLogger/src/vwid/api/WebsiteAPI.php on line 44" (EXCEPTION) in "/home/pi/IDDataLogger/src/webutils/Form.php" at line 11
> 21:31:02.946350 [EMERGENCY] CRASHED WHILE STARTING; TRYING TO SHUTDOWN SAFELY
> 21:31:02.948480 [INFO] Shutting down...
> 21:31:02.950400 [CRITICAL] Forcibly shutting down while starting!
> pi@raspberrypi:~/IDDataLogger $ 

Any clue what goes wrong?
Thanks again.

**Comment by robske110** [comment]
That error message usually points to an invalid/wrong E-Mail address. Did you enter your email address correctly in Step 5?
You can check what the saved email is by executing `cat ./config/config.json`.

**Comment by ArthurBijGithub** [comment]
Resolved! Thanks a lot. I feel a little silly asking for support and not reading the FAQ.
Sorry for that. It's my first stept info the world of Github.
Still very educational for me.

**Comment by robske110** [comment]
No problem! Welcome to GitHub!  Asking is never silly.
What was the issue in the end? And since you're one of the few who has gone through the manual installation, do you have any remarks about the guide / the process where it could maybe be clarified or improved?
If you have any remaining questions, don't hesitate to ask.

Since your new to GitHub: Especially large projects often don't accept support requests via the GitHub issue tracker, due to notification issues (all watchers will be notified). These then usually have some sort of policy written down somewhere, but it can be missed and be confusing for new users. Just though I'd give you that with you on your way.
(This project does not have such a policy, since I personally think most problems users have are actually "bugs", usually in form of bad documentation or non-user friendly error messages.)

**Comment by ArthurBijGithub** [comment]
On the error: I don't know. Username & password worked fine in my iOS WeConnectID-app and were apperently rejected when using the RPi. I did reset the password online and entered the new password in both the WeConnect-app and on the RPi and both are working now.
On the manual installation guide I can give you my opinion. Is this to be done in this topic or should I preferable use some other GitHub-feature? I guess I can make suggestions to make it easier to go through the steps for non real techies like myself. Being a commercial productmanager in the telecom-business, I have other skills :-)

**Comment by robske110** [comment]
Weird that changing the password fixed the issue - it could be that by doing so you might have accepted some new privacy terms&conditions, which might have fixed the issue.
Thanks for offering to give feedback on the guides, I really appreciate it.
I've opened a "discussion" here: https://github.com/robske110/IDDataLogger/discussions/16 (New GitHub feature, new for me too.)

**Comment by ArthurBijGithub** [comment]
I'm sorry for being quiet so long. I've been involved in some other things and could spend time on this. Are you still interested in my suggestions? The link to the 'discussion' doesn't work anymore. Did you remove it or has this meen removed?
Please let me know and I'll write down my observations.

**Comment by robske110** [comment]
No worries! I've fixed the link.
