### ISSUE TITLE
Widget does not show data when fast charging

### ISSUE THREAD

**Issue by simonCGN** [robske110/IDDataLogger#17]
Hi, while connected DC 100KW the widget does not show charging data.
![image](https://user-images.githubusercontent.com/31488296/115575610-04560200-a2c3-11eb-8a63-cc9d8ece3798.png)

**Comment by simonCGN** [comment]
![image](https://user-images.githubusercontent.com/31488296/115575794-2ea7bf80-a2c3-11eb-815d-a3e944af5009.jpeg)

**Comment by simonCGN** [comment]
2021-04-21 17:01:45: {"time":"2021-04-21T14:53:40+00:00","batterySOC":"9","remainingRange":62,"remainingChargingTime":0,"chargeState":"readyForCharging","chargePower":"0.0","chargeRateKMPH":0,"targetSOC":"100","plugConnectionState":"connected","plugLockState":"locked","remainClimatisationTime":0,"hvacState":"off","hvacTargetTemp":"19.0","lastChargeStartTime":"2021-04-21T14:31:34+00:00"}

**Comment by simonCGN** [comment]
Ok, there was some delay in presenting all data. Works now.
![image](https://user-images.githubusercontent.com/31488296/115576149-86462b00-a2c3-11eb-8526-18a08c549a34.png)

**Comment by robske110** [comment]
At the moment the server might, in a worst case scenario take 10 minutes to detect a charging session and increase its polling rate. On top of that iOS might introduce another delay through widget updating which could delay everything up to 25mins in the absolute worst case. I am working on getting this resolved in the future.
In the meantime you can decrease base-updaterate in config.json to 300. I am running my IDDataLogger with that value. I am being a bit more conservative in the default config to avoid hitting unknown rate limits (and unnecessarily stress VW servers).
https://github.com/robske110/IDDataLogger/blob/master/config/config.example.json#L5
https://github.com/robske110/IDDataLogger/blob/master/docs/config.md#configjson

Btw, did you know that you can add the IDView website as an app to your home screen? You can simply open it in safari, press the share button and select Add to home screen.
