### ISSUE TITLE
Unable to fetch carPic.png

### ISSUE THREAD

**Issue by dewoert** [robske110/IDDataLogger#19]
First of all: Many thanks for this great tool !
Almost everything is working fine.
Only one issue left:
I can't get online pictures from my ID.3 (Pro) Business  (model 2021)
When I access the "garage" at volkswagen.de, my car is added, but also there are no pictures.
I guess that is the main reason ?
But perhaps you can provide tips on how to get the pictures active ?
(When i put another picture as carPic.png, is displays in the logger and also in the iOS Widget)
![screenshot_67](https://user-images.githubusercontent.com/18567064/125212379-5482a600-e2ad-11eb-887c-b0e59182d4ad.png)

**Comment by robske110** [comment]
The car Picture is fetched from the garage site of VW, so if VW does not display any picture there, IDDataLogger can also not automatically fetch it.
Apparently VW does not have proper pictures added for your exact model. (You could contact them about that, but it is probably not worth the effort)

I think the best thing to do is just find a nice promotional picture of your model and put it in data/carPic.png or you could take a picture of your own car with a camera :)

**Comment by CrazyHenk44** [comment]
I've put in a data/carPic.png, but what triggers it to be processed? Guess it needs to be read into the database or something?

**Comment by robske110** [comment]
It will be read into the database at each startup of the backend php process.
Be aware that browsers do cache this image for some time also, so you might need to clear your browser's cache / force reload the page to see it be reflected.
The iOS script caches it even more aggressively you need to set `forceImageRefresh` to true temporarily. (Remember to set it back to false!)

**Comment by CrazyHenk44** [comment]
Restarted the service and shift-reload the page fixed it, thanks a lot. Much better now :)
