### ISSUE TITLE
IDDatalogger seems to only can handle one car?

### ISSUE THREAD

**Issue by sailor1958** [robske110/IDDataLogger#20]
I have two cars, but I can only see one :(.

A function / setting there let me select a car based on ex. VIN number will be greate

Tahnks

**Comment by robske110** [comment]
Unfortunately in its current state it indeed only supports one car per instance. If you are running this on Docker it should be easy to setup a second instance of IDDataLogger with the other car's vin in the .env file.
If you run it on a raspberry pi, it is also possible to do with some general server/linux knowledge. I might try to write a guide on how to do this.
The vin setting is documented here: https://github.com/robske110/IDDataLogger/blob/master/docs/config.md#configjson
Note: You should avoid to change the vin setting on a IDDataLogger instance if it already collected data from another car.

While multi-car support is certainly something that should be implemented natively at some point, I don't see this happening soon with my limited time and lack of 2 vehicles to test.

**Comment by sailor1958** [comment]
Thanks for your response.
I'm running in a docker setup, so that I will do one instance for each car. It doesn't seem to be a big problem to do.
Multi-car support as a native thing is not needed, from my point of view, as long you can have more instances running.
