### ISSUE TITLE
feature request: default value N for generate API Keys

### ISSUE THREAD

**Issue by drego83** [robske110/IDDataLogger#3]
I think it would be easier, if the following two questions will be answered by N with default

> Do you want to generate an API key? (Y,N)
[Y]: N
We can now setup a user for the IDView (website with statistics about the car)
> Do you want to create an user? (Y,N)
[Y]: N

**Comment by robske110** [comment]
This prompt should not popup on every startup of the application, only on the initial startup, wehre I think the defaults make sense.
For a quick fix you can pass the nowizard option to start.sh: `./start.sh nowizard`
Can you share the output from `FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'carstatus'` and `FROM INFORMATION_SCHEMA.TABLES WHERE`?

**Comment by drego83** [comment]
localhost/INFORMATION_SCHEMA/TABLES/
 Zeige Datensätze 0 -  3 (4 insgesamt, Die Abfrage dauerte 0.0010 Sekunden.)

SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA="id3"

(`TABLE_CATALOG`, `TABLE_SCHEMA`, `TABLE_NAME`, `TABLE_TYPE`, `ENGINE`, `VERSION`, `ROW_FORMAT`, `TABLE_ROWS`, `AVG_ROW_LENGTH`, `DATA_LENGTH`, `MAX_DATA_LENGTH`, `INDEX_LENGTH`, `DATA_FREE`, `AUTO_INCREMENT`, `CREATE_TIME`, `UPDATE_TIME`, `CHECK_TIME`, `TABLE_COLLATION`, `CHECKSUM`, `CREATE_OPTIONS`, `TABLE_COMMENT`)

('def', 'id3', 'authKeys', 'BASE TABLE', 'InnoDB', 10, 'Dynamic', 0, 0, 16384, 0, 0, 0, NULL, '2021-02-27 06:25:13', NULL, NULL, 'utf8_general_ci', NULL, '', '')
('def', 'id3', 'carPictures', 'BASE TABLE', 'InnoDB', 10, 'Dynamic', 0, 0, 16384, 0, 0, 0, NULL, '2021-02-27 06:25:24', '2021-02-27 07:11:50', NULL, 'utf8_general_ci', NULL, '', '')
('def', 'id3', 'carStatus', 'BASE TABLE', 'InnoDB', 10, 'Dynamic', 0, 0, 16384, 0, 0, 0, NULL, '2021-02-27 06:22:54', '2021-02-27 08:33:19', NULL, 'utf8_general_ci', NULL, '', '')
('def', 'id3', 'users', 'BASE TABLE', 'InnoDB', 10, 'Dynamic', 0, 0, 16384, 0, 32768, 0, 2, '2021-02-27 06:24:58', '2021-02-27 08:13:15', NULL, 'utf8_general_ci', NULL, '', '')

**Comment by drego83** [comment]
AND the result of:
SELECT table_name FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'carstatus'

is empty

**Comment by drego83** [comment]
reason: carstatus != carStatus

**Comment by drego83** [comment]
perfect, tested, error fixed
