### ISSUE TITLE
ABRP Integration

### ISSUE THREAD

**Issue by CrazyHenk44** [robske110/IDDataLogger#32]
I've created a patch to integrate A Better Route Planner into your source. So I added an ABRP CarStatusUpdateReceiver that also receives the data you fetch, and then feeds it to ABRP via a get request. I've done my best to follow your method of working, adding a section to the readme, etc.

I hope you can consider applying the patch.
[abrp.txt](https://github.com/robske110/IDDataLogger/files/7542062/abrp.txt)

**Comment by johnnysl** [comment]
ABRP integration of data is a very coveted feature. Think this would massively push the popularity of the tool. @robske110 could you please add this?

**Comment by robske110** [comment]
I already had a (basic, but working) implementation on the [abrp-integration](https://github.com/robske110/IDDataLogger/tree/abrp-integration) branch. @CrazyHenk44 thank you very much for your contribution, not many people contribute code to open source projects and try to understand and follow the coding style and architecture while they're at it 👍 
I've contacted Jason from ABRP and got the ok to release the integration. I will try to polish the branch over the next few days and would love to have some people test it (I will post installation instructions here) and then merge it into the master branch.

**Comment by CrazyHenk44** [comment]
My patch is almost identical to your branch, amazing how to two people can come up with the same code :)
Anyhow, feel free to grab from my patch whatever you like. I think providing the car helps ABRP, so you might make that optional. 

And ABRP approved to make the api key public, so you can make that a constant, instead of a config item.

Also maybe take my documentation bit. 

Your POST method is nice, it was on my list to improve if you had accepted the patch. Does not expose the data in the URL, hence keeping the data encrypted during transport.

Also ABRP added  "est_battery_range" on my request, it shows when you click the car, so you can fill it with $status["remainingRange"]. 

I'm happy to test it for you and get some friends setup as well.

Thanks.

**Comment by tillsteinbach** [comment]
@CrazyHenk44 seems like you have a good contact to iternio. I asked if they can change the way it is decided if the API is shown connected/disconnected in ABRP.
It makes sense to send the time the data was recorded in the car in the APIs utc field and not the current time. But if you do so ABRP shows disconnected when the car is offline. Would be preferable that ABRP shows the connection state based on the last time the data was transmitted to the API. Maybe it is helpful if someone else is requesting this feature there too.

**Comment by CrazyHenk44** [comment]
Sure, will fire a mail. I reasoned that the data you receive is more or less the current data, or the last known good data before the car went offline, but still accurate. Hence it warrants to provide a current timestamp, but I feel your sentiment and fire a mail.

**Comment by CrazyHenk44** [comment]
Requested and mailed back and forth a few times. Don’t think it will change soon, but at least we brought it up.

for now I suggest we pass the current time there, to not confuse users.

**Comment by tillsteinbach** [comment]
Thank you! It is just wrong to provide a time (now) that the system already has. Hope they will change it.
I (author of VWsFriend project) will keep my implementation with the car timestamp. It is just making more accurate results, in particular while charging.

**Comment by robske110** [comment]
I will also likely keep sending the car timestamp: https://github.com/robske110/IDDataLogger/blob/abrp-integration/src/vwid/integrations/ABRP.php#L29

**Comment by CrazyHenk44** [comment]
Any update?

**Comment by CrazyHenk44** [comment]
Can I do something to get this merged?

**Comment by robske110** [comment]
Sorry to keep you hanging, I was really busy in the last few weeks.
I have opened PR #36, and am looking for testing & feedback :)
