### ISSUE TITLE
Docker how to on raspberry buster

### ISSUE THREAD

**Issue by JimKnopf1503** [robske110/IDDataLogger#33]
Hi!

I have problems running the IDDataLogger directly on my pi (login stuck without any message). So I'm trying the docker version.
In your manual: After creating the .env file the last command to execute is "docker compose up".
I dont know how it works on other systems, on my raspberry it hast to be "docker-compose up".
I never used docker and it took a while to find this out.
Finaly I got following errors:
W: GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.

I am running buster on my pi.
Best regards,
Burkhard

**Comment by robske110** [comment]
Something is wrong with your apt repositories. You say you are running buster, but your apt repos appear to be pointing to bullseye (the new upstream branch of raspbian). Maybe this helps: https://stackoverflow.com/questions/62473932/atleast-one-invalid-signature-was-encountered
Anyways, this is not an issue with IDDataLogger, there is something wrong with docker or your installation of raspbian.

Running docker on the pi is not what I usually recommend, especially on older PIs (slow) and with small SD cards (you could for example also be out of storage, which can also cause errors like that).

Could you elaborate more on the original issue when you tried to run it directly / without docker?

**Comment by JimKnopf1503** [comment]
Hi!

I solved my problem. When I'am right, IDDataLogger needs PHP8 or above. I setup openmediavault first. It uses nginx and needs PHP7. I now can handle it by switching nginx port to 81 an then install apache and php8.
My first shot was docker with the known problems.
Finaly: when phpinfo() shows, that php is lower than version 8, the loginpage of IDDataLogger do nothing.
I was trying to change to mysql, but the tables werent created correctly. Mysql would be easyer for my to backup (mysqldumper  now MyOOSDumper).
At the moment everything is fine for me. Thank you for your supprt and your work.
And sorry for my bad english ;-).
Best regards,
Burkhard
