### ISSUE TITLE
IDDataLogger stopped working after a power outage

### ISSUE THREAD

**Issue by Gualty** [robske110/IDDataLogger#37]
Hi,
15 days ago I was charging my ID at home and a power outage happened. From that moment IDDataLogger do not receive updates from my ID anymore. On IDDataLogger seems it is still in charge from that moment whit the same battery percentage.

I tried to reboot the raspberry where is running IDDataLogger, I also updated IDDataLogger and the software of raspbian but the issue persists.

My ID is reachable from the ID Connect app and from other apps that uses the API so the issue is with IDDataLogger.

How can I fix it?

Best regards

**Comment by JimKnopf1503** [comment]
Hi!
Check, if the service is still running (again):
sudo service iddatalogger status

If not, the service did not start again after reboot.
Ty:
sudo systemctl enable iddatalogger

Then reboot the Raspberry and check again if the service is running.

Burkhard

**Comment by Gualty** [comment]
Hi,
thank you for your answer. I tried the suggested steps but issue persists.

I also rebooted the raspberry but when I run "sudo service iddatalogger status" this message appear:

```
● iddatalogger.service - ID DataLogger php backend
   Loaded: loaded (/etc/systemd/system/iddatalogger.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) since Wed 2021-12-29 10:53:00 CET; 1s ago
  Process: 1328 ExecStart=/home/pi/IDDataLogger/start.sh (code=exited, status=0/SUCCESS)
 Main PID: 1328 (code=exited, status=0/SUCCESS)
```

**Comment by JimKnopf1503** [comment]
Hi!
Ok, I think the IDDataLogger is running. Did you try the mobile app WeConnect ID?
In the last weeks there was an update in the contracts that mus be accepted in the app.
Do you get actual data in WeConnect ID? If you do, we shuld wait for an answer from robske.

Burkhard

**Comment by Gualty** [comment]
> Hi!
> 
> Ok, I think the IDDataLogger is running. Did you try the mobile app WeConnect ID?
> 
> In the last weeks there was an update in the contracts which must be accepted in the app.
> 
> Another try to check if everything is ok:
> 
> cd /home/pi/IDDataLogger
> 
> ./start.sh
> 
> In this terminal window you can see if the iddatalogger is polling values from VW. 
> 
> It should look like this:
> 
> 
> 
> - loading Logger...
> 
> 11:40:32.457683 [INFO] Starting ID DataLogger Version v0.0.6-InDev (9ea6928a04105b444726a2a743a1e30b9c15f63c)...
> 
> Loading Main...
> 
> 11:40:32.476740 [INFO] Reading config...
> 
> 11:40:32.476967 [INFO] Connecting to db...
> 
> Loading DatabaseConnection...
> 
> Loading QueryCreationHelper...
> 
> Loading DBmigrator...
> 
> Loading CurlWrapper...
> 
> Loading API...
> 
> Loading CarPictureHandler...
> 
> Loading CarStatusWrittenUpdateReceiver...
> 
> Loading ChargeSessionHandler...
> 
> 11:40:32.574504 [INFO] Building past charge sessions from 2021-12-27 10:57:12...
> 
> 11:40:32.581518 [INFO] Plugged car in at 2021-12-29 07:46:23
> 
> Loading ChargeSession...
> 
> 11:40:32.582673 [INFO] Started charging at 2021-12-29 07:46:23
> 
> Loading CarStatusFetcher...
> 
> 11:40:32.587917 [INFO] Logging in...
> 
> Loading LoginInformation...
> 
> Loading MobileAppAPI...
> 
> Loading HTTPUtils...
> 
> Loading Form...
> 
> Loading CarStatusUpdateReceiver...
> 
> Loading CarStatusWriter...
> 
> 11:40:37.390725 [INFO] Done. Startup took 5.2770481109619s
> 
> 11:40:37.390951 [INFO] Ready!
> 
> 11:40:37.391104 [INFO] Fetching car status...
> 
> 11:40:38.166040 [NOTICE] Could not find expected key 'zoneRearLeftEnabled' in carStatusData. Unexpected changes in older or newer car software can cause this!
> 
> 11:40:38.167400 [NOTICE] Could not find expected key 'zoneRearRightEnabled' in carStatusData. Unexpected changes in older or newer car software can cause this!
> 
> 11:40:38.168300 [INFO] Writing new data for timestamp 2021-12-29T10:31:28
> 
> 
> 
> 
> 
> Now you should see actual data in the web frontend of IDDataLogger. If you do, there is a problem with autostart of IDDataLogger. If you dont see actual data in the web frontend but in WeConnect ID, there my be some other problem. May be reinstalling may solve the problem. I don't know if you may loose old logged data.
> 
> 
> 
> If this all does not help, we shuld wait for an answer from robske.
> 
> 
> 
> 
> 
> Burkhard


Hi,
Yes the We Connect ID app is working normally and other apps that uses API is working correctly.

**Comment by robske110** [comment]
@Gualty From the output from the `sudo service iddatalogger status`
`Active: activating (auto-restart) since Wed 2021-12-29 10:53:00 CET; 1s ago`
This line means that systemctl is trying to start IDDataLogger, but that it keeps crashing.

You can display the log from systemctl to find the exact error message
`sudo journalctl -u iddatalogger`
which is documented [here](https://github.com/robske110/IDDataLogger/blob/master/docs/beginnerguide.md#finishing-set-up) or try the commands @JimKnopf1503 sent
```
cd /home/pi/IDDataLogger
./start.sh
```

This is probably just another case that will be resolved by logging in on the Volkswagen website with you account and accepting all privacy polices and TOS that pop up. (https://github.com/robske110/IDDataLogger/wiki/FAQ-and-frequent-problems#resolving-most-login-issues)
[This coincides with restarts/power outages, because IDDataLogger then needs to do a full re-login, which won't work with outstanding unaccepted privacy policy or TOS changes]

Thank you @JimKnopf1503 for helping!

**Comment by Gualty** [comment]
Hi @robske110,

I followed your steps and the issue is now solved.

Thank you for your support!

Best regards
Gualtiero
