### ISSUE TITLE
It seems VW changed the login protocol

### ISSUE THREAD

**Issue by JimKnopf1503** [robske110/IDDataLogger#45]
Hi!

I think VW changed the login protocoll.
After sending the emailadress, there is no "Form" provided. 
The response starts like:
`<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport"
          content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    <meta name="identitykit" content="loginAuthenticate"/>
    
<script type="text/javascript">(window.NREUM||(NREUM={})).init={privacy:{cookies_enabled:false},ajax:{deny_list:[]}};(window.NREUM||(NREUM={})).loader_config={xpid:"VgMDVl5RARACVlhSDwgFVA==",licenseKey:"NRJS-ecd5929e8859410bbd9",applicationID:"22908922"};window.NREUM||(NREUM={}),__nr_require=function(t,e,n){function r(n){if(!e[n]){var i=e[n]={exports:{}};t[n][0].call(i.exports,function(e){var i=t[n][1][e];return r(i||e)},i,i.exports)}return e[n].exports}if("function"==typeof __nr_require)return __nr_require;for(var i=0;i<n.length;i++)r(n[i]);return r}({1:[function(t,e,n){function r(t){try{s.console&&console.log(t)}catch(e){}}var i,o=t("ee"),a=t(28),s={};try{i=localStorage.getItem("__nr_flags").split(","),console&&"function"==typeof console.log&&(s.console=!0,i.indexOf("dev")!==-1&&(s.dev=!0),i.indexOf("nr_dev")!==-1&&(s.nrDev=!0))}catch(c){}s.nrDev&&o.on("internal-error",function(t){r(t.stack)}),s.dev&&o.on("fn-err",function(t,e,n){r(n.stack)}),s.dev&&(r("NR AGENT IN DEVELOPMENT MODE"),r("flags: "+a(s,function(t,e){return t}).join(", ")))},{}],2:[function(t,e,n){function r(t,e,n,r,s){try{p?p-=1:i(s||new UncaughtException(t,e,n),!0)}catch(f){try{o("ierr",[f,c.now(),!0])}catch(d){}}return"function"==typeof u&&u.apply(this,a(arguments))}function UncaughtException(t,e,n){this.message=t||"Uncaught error with no additional information",this.sourceURL=e,this.line=n}function i(t,e){var n=e?null:c.now();o("err",[t,n])}var o=t("handle"),a=t(29),s=t("ee"),c=t("loader"),f=t("gos"),u=window.onerror,d=!1,l="nr@seenError";if(!c.disabled){var p=0;c.features.err=!0,t(1),window.onerror=r;try{throw new Error}catch(h){"stack"in h&&(t(10),t(9),"addEventListener"in window&&t(6),c.xhrWrappable&&t(11),d=!0)}s.on("fn-start",function(t,e,n){d&&(p+=1)}),s.on("fn-err",function(t,e,n){d&&!n[l]&&(f(n,l,function(){return!0}),this.thrown=!0,i(n))}),s.on("fn-end",function(){d&&!this.thrown&&p>0&&(p-=1)}),s.on("internal-error",function(t){o("ierr",[t,c.now(),!0])})}},{}],3:[function(t,e,n){var r=t("loader");r.disa`

I will try to findout how it wokrs now but I'am not a java guy.
Burkhard

**Comment by dasTholo** [comment]
Same here
Maybe Log can help

```
[11:37:37] INFO: Starting IDDataLogger...
}Loading Logger...
11:37:37.941293 [INFO] Starting ID DataLogger Version v0.0.6-InDev (705d3b2cc97a7d2a941d98bcaacf05c8ad6614f4)...
Loading Main...
11:37:37.945091 [INFO] Reading config...
11:37:37.945436 [INFO] Connecting to db...
Loading DatabaseConnection...
Loading QueryCreationHelper...
Loading DBmigrator...
Loading CurlWrapper...
Loading API...
Loading CarPictureHandler...
11:37:38.164107 [INFO] Fetching carPicture (this will take a while...)
Loading WebsiteAPI...
Loading LoginInformation...
Loading HTTPUtils...
Loading Form...
Loading IDAPIException...
Loading IDLoginException...
Loading ErrorUtils...
11:37:38.929566 [CRITICAL] robske_110\vwid\api\exception\IDLoginException: "Unable to login. Check login information (e-mail)! (Could not find credentialsForm)" (EXCEPTION) in "/usr/src/IDDataLogger/src/vwid/api/WebsiteAPI.php" at line 45
11:37:38.929943 [WARNING] Failed to automatically fetch the carPicture! You can substitute data/carPic.png manually.
Loading CarStatusWrittenUpdateReceiver...
Loading ChargeSessionHandler...
11:37:38.952456 [INFO] Building past charge sessions from 2022-01-27 14:33:56...
Loading CarStatusFetcher...
11:37:38.960643 [INFO] Logging in...
Loading MobileAppAPI...
11:37:39.713180 [CRITICAL] robske_110\vwid\api\exception\IDLoginException: "Unable to login. Check login information (e-mail)! (Could not find credentialsForm)" (EXCEPTION) in "/usr/src/IDDataLogger/src/vwid/api/MobileAppAPI.php" at line 55
11:37:39.713392 [EMERGENCY] CRASHED WHILE STARTING; TRYING TO SHUTDOWN SAFELY
11:37:39.713443 [INFO] Shutting down...
11:37:39.713476 [CRITICAL] Forcibly shutting down while starting!
[cmd] /bin/bash exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by robske110** [comment]
I hope this should be fixed in the commit https://github.com/robske110/IDDataLogger/commit/f23b56dd329db76e1b24fa7223ba33014f0de8b3!
Please test after updating. It would also help me if you could try removing data/carPic.png and see if fetching it works too. For me it works with no changes, but from the output from @dasTholo there could be possibly issues there too.

If the issue persists set logging.debug-enable to true and post the output here. You can also additionally set logging.curl-verbose to true and send me the output in a PM (on the forums here: https://github.com/robske110/IDDataLogger/wiki/Getting-help)

**Comment by JimKnopf1503** [comment]
Hi Rob!
Thanks for the verry fast solution!
It is working for me.
Well done.

Burkhard

**Comment by robske110** [comment]
@dasTholo I now also fixed the fetching of the carPic. I didn't pay attention while trying to reproduce it.
https://github.com/robske110/IDDataLogger/commit/41ab162470d722dea033ee54537e56bd2d7a7ced

**Comment by UnbekanntesPferd** [comment]
Did they change again?
Yesterday I made on update on my ID.3 to 3.8, now the login does not work anymore:

`16:44:32.962830 [INFO] Building past charge sessions from 2025-08-04 13:07:59...
Loading CarStatusFetcher...
16:44:32.973730 [INFO] Logging in...
Loading LoginInformation...
Loading MobileAppAPI...
Loading HTTPUtils...
Loading Form...
Loading IDAPIException...
Loading IDLoginException...
Loading ErrorUtils...
16:44:32.821672 [CRITICAL] robske_110\vwid\api\exception\IDLoginException: "Unable to login. Check login information (password)! See FAQ if issue persists. (Could not find location header)" (EXCEPTION) in "/src/vwid/api/MobileAppAPI.php" at line 51
16:44:32.821788 [EMERGENCY] CRASHED WHILE STARTING; TRYING TO SHUTDOWN SAFELY
16:44:32.821807 [INFO] Shutting down...
16:44:32.821819 [CRITICAL] Forcibly shutting down while starting!`
