### ISSUE TITLE
ID Software 3.0 feature support

### ISSUE THREAD

**Issue by thiasB** [robske110/IDDataLogger#49]
Hi,
will this project ever get support for the upcoming features of ID Software 3.0+. I'd love to see parking location, total distance driven, driving sessions and car lock status integrated - at least to have it stored it in the database.
Best,
M.

**Comment by robske110** [comment]
I currently don't have access to a car with software 3.0 because VW is very slow with their rollout.

**Comment by thiasB** [comment]
Me neither, but it seems you haven't abandoned this project yet. I'm looking forward receiving 3.0 on both of our cars

**Comment by thiasB** [comment]
3.0 arrived here. Let me know if you need access

**Comment by robske110** [comment]
The car I have access to also received the 3.0 update a few weeks ago, but honestly I can't see any new (interesting) data being transmitted by the car. Does the locate your car feature work for you (in the app)?

**Comment by thiasB** [comment]
Thanks for looking into it. 
- SoC and SOC while charging is not captured anymore. Range, charging session, charging power, target SoC is all being stored to the database
- App shows parking location

**Comment by thiasB** [comment]
Also, I found this in the logs
```
Jan 15 22:59:10 iddatalogger[3467628]: #033[97m22:59:10.939316 #033[0m#033[96m[INFO] Fetching car status...#033[0m
Jan 15 22:59:11 iddatalogger[3467628]: #033[97m22:59:11.276607 #033[0m#033[93m[NOTICE] Could not find expected key 'hvacWithoutExternalPower' in carStatusData. Unexpected changes in older or newer car software can cause this!#033[0m
Jan 15 22:59:11 iddatalogger[3467628]: #033[97m22:59:11.276666 #033[0m#033[93m[NOTICE] Could not find expected key 'zoneRearLeftEnabled' in carStatusData. Unexpected changes in older or newer car software can cause this!#033[0m
Jan 15 22:59:11 iddatalogger[3467628]: #033[97m22:59:11.276673 #033[0m#033[93m[NOTICE] Could not find expected key 'zoneRearRightEnabled' in carStatusData. Unexpected changes in older or newer car software can cause this!#033[0m
```

**Comment by thiasB** [comment]
`readyForCharging` in `chargestate` was renamed to `notReadyForCharging`. I can see the data now
