### ISSUE TITLE
VW changed the first login page, getting now error 404

### ISSUE THREAD

**Issue by JimKnopf1503** [robske110/IDDataLogger#54]
Hi!

Volkswagen changed again the protocol, now the get login page.

"https://login.apps.emea.vwapps.io/authorize?nonce=" +code_challenge+ "&redirect_uri=weconnect://authenticated" 
Getting HTTP Error 404 the last days. Now the request wait endless.

Burkhard

**Comment by robske110** [comment]
Fixed in https://github.com/robske110/IDDataLogger/commit/a1285b709b86d5cf73fcf61b18f465428aeba1fb and https://github.com/robske110/IDDataLogger/commit/1521100ba1d174f7c35ec0dbd843cbd1982b5be1
