### ISSUE TITLE
Suggestion: version information in Backend and Frontend

### ISSUE THREAD

**Issue by derGali** [robske110/IDDataLogger#6]
It would be helpful if the backend and frontend script would display the current version.

So one can know if there is a new release or if your update/restart was successful.

Backend script: when starting
Frontend: small, in a corner

**Comment by robske110** [comment]
The backend script already displays the Version: https://github.com/robske110/IDDataLogger/blob/master/src/vwid/Server.php#L76
Making that available on the frontend makes sense, I will look into implementing that soon.
