### ISSUE TITLE
Changed table definitions prevent start

### ISSUE THREAD

**Issue by derGali** [robske110/IDDataLogger#7]
I just pulled the latest commit. On starting start.sh I get this error message:
```
[...] ON CONFLICT (pictureID) DO UPDATE SET carPicture = excluded.carPicture failed: SQLSTATE[42703]: Undefined column: 7 ERROR: column "pictureid" of relation "carpictures" does not exist LINE 1: INSERT INTO carPictures(
pictureID, carPicture) VALUES('defau... ^ [42703]" (EXCEPTION) in "/root/IDDataLogger/src/vwid/DatabaseConnection.php" at line 68
```

In my database the column has the name "id", not "pictureID".

**Comment by derGali** [comment]
Manually renaming
carpictures.id TO carpictures.pictureid
authkeys.key TO authkeys.authkey
works

**Comment by robske110** [comment]
You probably had a very old version running already with the old incompatible column names.
I promise to do auto-db migration from now on :)
