### ISSUE TITLE
RPI Zero W Illegal instruction

### ISSUE THREAD

**Issue by zigad** [robske110/IDDataLogger#9]
Hi!

I tried to install IDDataLogger on a fresh install on Raspberry Pi Zero W with Debian Lite but i get an error when I try to run this command:
You can now enter ./start.sh, which will start the ID DataLogger.

I get an Illegal instruction

```
pi@Raspi-Server:~/IDDataLogger $ ./start.sh
Illegal instruction
```

The same issue happens if I try manual steps:
We'll need to tell it the database details and our VW account login information. We'll change into the directory of the program by executing cd IDDataLogger and then run the config wizard with ./config-wizard.sh --allow-insecure-http

When I enter ./config-wizard.sh --allow-insecure-http I get the same error Illegal instruction

```
pi@Raspi-Server:~/IDDataLogger $ ./config-wizard.sh --allow-insecure-http
Illegal instruction
```

**Comment by robske110** [comment]
The raspberry pi zero is not properly supported, because some packages are not built for its cpu.
You could build these from source, but that would be a relatively lengthy and time consuming process.
